version: "2"

services:
  app:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run build && while :; do npm run watch; sleep 10; done"

  examples:
    image: node:14
    volumes:
      - .:/examples
    working_dir: /examples
    command: bash -c "cd /examples && git clone https://github.com/phaserjs/examples.git && cd examples && npm install && npm start"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
      - examples

networks:
  default:
    name: my-network



events { worker_connections 1024; }

http {
  server {
    listen 80;

    location / {
      proxy_pass http://app:3000;
    }

    location /examples {
      proxy_pass http://examples:3001;
    }
  }
}

