# .travis.yml

sudo: required

language: node_js

node_js:
  - '10'

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm run lint
  - npm run build

branches:
  only:
    - master

notifications:
  email:
    on_failure: always

